npmRegistries:
  //gitlab.com/api/v4/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "${SUPERSIDE_NPM_AUTH_TOKEN}"

npmScopes:
  superside:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"
